services:
  spring:
    build: ./backend/spring-api
    container_name: illu-spring-api
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/illu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: illu_user
      SPRING_DATASOURCE_PASSWORD: 1234

  frontend:
    build: ./frontend
    container_name: illu-frontend
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    container_name: illu-mysql
    environment:
      MYSQL_DATABASE: illu
      MYSQL_USER: illu_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
